import type { Metadata } from 'next';
import '@/styles/global.css';
import { ReactNode } from 'react';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'en_US',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          'bg-dark text-white min-h-screen m-0 flex place-items-center min-w-[320px]'
        }
      >
        {children}
      </body>
    </html>
  );
}
